reduced the scope of all local variables using the 'local' keyword, and made all local variable names lowercase

diff --git a/bookmark b/bookmark
--- a/bookmark
+++ b/bookmark
@@ -50,25 +50,25 @@ bookmark_list_bookmarks() {
 		while read line    
 		do    
 			split=(${line//:/ })
-			SAVED_MARK=${split[0]}
-			LOCATION=${split[1]}
-			echo -e $SAVED_MARK "\t->\t" $LOCATION
+			saved_mark=${split[0]}
+			location=${split[1]}
+			echo -e $saved_mark "\t->\t" $location
 		done < ~/.bookmarks
 	fi
 }
 
 mark() {
 	# parse options
-	F_FLAG=false
-	L_FLAG=false
+	local f_flag=false
+	local l_flag=false
 
 	while [ $# -gt 0 ]
 	do
 	    case "$1" in
-	    	(-f) F_FLAG=true;;
-	    	(-l) L_FLAG=true;;
-	    	(-h) help_message; return 0;;
-	    	(--help) bookmark_mark_message; return 0;;
+	    	(-f) f_flag=true;;
+	    	(-l) l_flag=true;;
+	    	(-h) bookmark_mark_help_message; return 0;;
+	    	(--help) bookmark_mark_help_message; return 0;;
 	    	(-*) echo "$0: error - unrecognized option $1" 1>&2; return 1;;
 	    	(*)  break;;
 	    esac
@@ -76,7 +76,7 @@ mark() {
 	done
 
 	# if list option selected, list bookmarks list existing bookmarks
-	if [[ $L_FLAG = true ]]; then
+	if [[ $l_flag = true ]]; then
 		bookmark_list_bookmarks
 		return 0
 	fi
@@ -87,18 +87,18 @@ mark() {
 		return 1
 	fi
 
-	NEW_MARK="$1"
+	local new_mark="$1"
 	shift
 
 	# extract full path of bookmark location
 	if [[ "$#" == "0" ]]; then
-		LOCATION=$(pwd)
+		local location=$(pwd)
 	else
 		if [[ -d $1 ]]; then
-			LOCATION="$(cd $1; pwd)"
+			local location="$(cd $1; pwd)"
 		else 
 			# resolve full path to file
-			LOCATION=$(python -c "import os; print os.path.abspath(\"$1\")")
+			local location=$(python -c "import os; print os.path.abspath(\"$1\")")
 		fi
 		shift
 	fi
@@ -113,10 +113,10 @@ mark() {
 	if [ -f ~/.bookmarks ]; then
 		while read line    
 		do    
-			split=(${line//:/ })
-			SAVED_MARK=${split[0]}
-			if [ $SAVED_MARK = $NEW_MARK -a $F_FLAG = false ]; then
-				echo "error: bookmark '$NEW_MARK' already used." 1>&2
+			local split=(${line//:/ })
+			local saved_mark=${split[0]}
+			if [ $saved_mark = $new_mark -a $f_flag = false ]; then
+				echo "error: bookmark '$new_mark' already used." 1>&2
 				return 1
 			else 
 				marks+=($line)
@@ -124,7 +124,7 @@ mark() {
 		done < ~/.bookmarks
 	fi
 
-	marks=(${marks[@]} $NEW_MARK:$LOCATION)
+	local marks=(${marks[@]} $new_mark:$location)
 
 	rm -rf ~/.bookmarks
 	touch ~/.bookmarks
@@ -136,25 +136,25 @@ mark() {
 
 unmark() {
 	# parse options
-	A_FLAG=false
+	local a_flag=false
 	while [ $# -gt 0 ]
 	do
 	    case "$1" in
-	    	(-h) help_message; return 0;;
-	    	(-a) A_FLAG=true;;
-	    	(--help) help_message; return 0;;
+	    	(-h) bookmark_unmark_help_message; return 0;;
+	    	(-a) a_flag=true;;
+	    	(--help) bookmark_unmark_help_message; return 0;;
 	    	(-*) echo "$0: error - unrecognized option $1" 1>&2; return 1;;
 	    	(*)  break;;
 	    esac
 	    shift
 	done
 
-	if [ "$#" == "0" -a $A_FLAG = false ]; then
+	if [ "$#" == "0" -a $a_flag = false ]; then
 		echo "error: you must supply a name for the bookmark" 1>&2; return 1;
 	fi
 
 	# parse arguments
-	NEW_MARK="$1"
+	local new_mark="$1"
 	shift
 
 	if  (($# > 0)); then
@@ -162,13 +162,13 @@ unmark() {
 	fi
 
 	# accumulate all bookmarks other than one selected for removal
-	marks=()
+	local marks=()
 	if [ -f ~/.bookmarks ]; then
 		while read line    
 		do    
-			split=(${line//:/ })
-			SAVED_MARK=${split[0]}
-			if [ ! $SAVED_MARK = "$NEW_MARK" -a "$A_FLAG" = false ]; then
+			local split=(${line//:/ })
+			local saved_mark=${split[0]}
+			if [ ! $saved_mark = "$new_mark" -a "$a_flag" = false ]; then
 				marks+=($line)
 			fi
 		done < ~/.bookmarks
@@ -187,8 +187,8 @@ go() {
 	while [ $# -gt 0 ]
 	do
 	    case "$1" in
-	    	(-h) help_message;;
-	    	(--help) bookmark_goto_help_message;;
+	    	(-h) bookmark_goto_help_message; return 0;;
+	    	(--help) bookmark_goto_help_message; return 0;;
 	    	(-*) echo "$0: error - unrecognized option $1" 1>&2; return 1;;
 	    	(*)  break;;
 	    esac
@@ -201,25 +201,25 @@ go() {
 	elif (( $# > 1)); then
 		echo "error: too many arguments" 1>&2; return 1;
 	else
-		MARK="$1"
+		local mark="$1"
 		shift
 	fi
 
 	# search for bookmark
-	marks=()
-	found=false
+	local marks=()
+	local found=false
 	if [ -f ~/.bookmarks ]; then
 		while read line    
 		do    
-			split=(${line//:/ })
-			SAVED_MARK=${split[0]}
-			LOCATION=${split[1]}
-			if [ $SAVED_MARK = $MARK ]; then
-				if [ -d $LOCATION ]; then
-					cd $LOCATION;
+			local split=(${line//:/ })
+			local saved_mark=${split[0]}
+			local location=${split[1]}
+			if [ $saved_mark = $mark ]; then
+				if [ -d $location ]; then
+					cd $location;
 					found=true
-				elif [-f $LOCATION ]; then
-					$LOCATION;
+				elif [-f $location ]; then
+					$location;
 					found=true
 				else
 					echo "error: invalid bookmark" 1>&2;
@@ -237,21 +237,21 @@ go() {
 
 
 bookmark_list() {
-	LIST=""
+	local list=""
 	while read line    
 	do    
-		split=(${line//:/ })
-		SAVED_MARK=${split[0]}
-		LIST=$SAVED_MARK" "$LIST 
+		local split=(${line//:/ })
+		local saved_mark=${split[0]}
+		list=$saved_mark" "$list 
 	done < ~/.bookmarks
-	echo $LIST
+	echo $list
 }
 
 bookmark_autocomplete()
 {
     local cur=${COMP_WORDS[COMP_CWORD]}
-    MARKS=$( bookmark_list )
-    COMPREPLY=( $(compgen -W "$MARKS" -- $cur) )
+    local marklist=$( bookmark_list )
+    COMPREPLY=( $(compgen -W "$marklist" -- $cur) )
 }
 
 complete -F bookmark_autocomplete mark
